# Generated by Django 4.2.4 on 2023-10-15 20:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(max_length=20)),
                ('city', models.CharField(default='Mahdia', max_length=100)),
                ('date_b', models.DateField(blank=True, null=True)),
                ('interests', models.CharField(blank=True, choices=[('Phone & Tablet', 'Phone & Tablet'), ('Cooking & Culinary Arts', 'Cooking & Culinary Arts'), ('Health beauty', 'Health beauty'), ('Electronics', 'Electronics'), ('Supermarket', 'Supermarket'), ('Mode', 'Mode'), ('Informatique', 'Informatique'), ('Auto & Moto', 'Auto & Moto'), ('Home & Office', 'Home & Office'), ('Video Games & Consoles', 'Video Games & Consoles'), ('Sport stuff', 'Sport stuff')], max_length=80, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Masculin'), ('f', 'Féminin')], max_length=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest', models.CharField(choices=[('Phone & Tablet', 'Phone & Tablet'), ('Cooking & Culinary Arts', 'Cooking & Culinary Arts'), ('Health beauty', 'Health beauty'), ('Electronics', 'Electronics'), ('Supermarket', 'Supermarket'), ('Mode', 'Mode'), ('Informatique', 'Informatique'), ('Auto & Moto', 'Auto & Moto'), ('Home & Office', 'Home & Office'), ('Video Games & Consoles', 'Video Games & Consoles'), ('Sport stuff', 'Sport stuff')], max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('price', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(default='Mode', max_length=150, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('num_bids', models.PositiveIntegerField(default=-1)),
                ('image', models.ImageField(upload_to='images/')),
                ('interests', models.CharField(blank=True, choices=[('Phone & Tablet', 'Phone & Tablet'), ('Cooking & Culinary Arts', 'Cooking & Culinary Arts'), ('Health beauty', 'Health beauty'), ('Electronics', 'Electronics'), ('Supermarket', 'Supermarket'), ('Mode', 'Mode'), ('Informatique', 'Informatique'), ('Auto & Moto', 'Auto & Moto'), ('Home & Office', 'Home & Office'), ('Video Games & Consoles', 'Video Games & Consoles'), ('Sport stuff', 'Sport stuff')], max_length=80, null=True)),
                ('user_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=50)),
                ('comment_id_u', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('comment_title_l', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing')),
                ('user', models.ForeignKey(default='Cha23', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
